---
additional_packages:
  - screen
  - git
  - https://s3.{{ region| default("eu-west-2") }}.amazonaws.com/amazon-ssm-{{ region| default("eu-west-2") }}/latest/linux_amd64/amazon-ssm-agent.rpm
  - python-pip
  - python3-pip
  - libselinux-python
  - libsemanage-python
  - policycoreutils-python
  - jq

pip_install_packages:
  - name: pip
    state: latest
    umask: "0022"
  - name: ansible
    version: "2.10.6"
    umask: "0022"
  - name: selinux
    umask: "0022"
  - name: j2cli
    umask: "0022"

epel_repo_url: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm"
epel_repo_gpg_key_url: "/etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-7"

clamav_mirror: http://clamav-mirror.sharedservices.aws.internal

cis_enable_rsyslog: false
cis_apply_level_2_profile: true
cis_level_1_exclusions:
  - "5.2.15" #Allowed users/groups
  - "5.4.1.1" #password expiry
  - "5.4.1.4" #inactive password lock
  # Mount options
  - "1.1.2" 
  - "1.1.3"
  - "1.1.4"
  - "1.1.5"
  - "1.1.6"
  - "1.1.7"
  - "1.1.8"
  - "1.1.9"
  - "1.1.10"
  - "1.1.11"
  - "1.1.12"
  - "1.1.13"
  - "1.1.14"
  - "1.1.15"
  - "1.1.16"
  - "1.1.17"
  - "3.4.2" #/etc/hosts.allow
  - "3.4.3" #/etc/hosts.deny
cis_level_2_exclusions: 
  - "6.1.1"

## Nagios Variables
nrpe_allowed_hosts:
  - "127.0.0.1"
  - "10.44.12.0/24"
  - "10.44.13.0/24"	
  - "10.44.14.0/24"
nrpe_plugin_packages:
  - nagios-plugins-nrpe
  - nagios-plugins
  - nagios-plugins-disk
nrpe_command:
  check_disk_all:
    script: check_disk
    option: -w 80 -c 90
nrpe_config: 
  dont_blame_nrpe: 0
