Vagrant.configure("2") do |config|
  config.vm.box = "gbailey/amzn2"
  config.vm.define "amzn2-base"
  config.vm.provider "virtualbox" do |v|
    #Needs a reasonable RAM allocation or ClamAV daemon fails first time start
    v.memory = 4096 
    v.cpus = 2
  end

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "../playbook.yml"
  end
end
