---
- hosts: amzn2-base
  become: true
  collections: 
    - ch-collections.base
  pre_tasks:
    - name: Updating System Packages Before Ansible Run
      yum:
        name: '*'
        state: latest

  roles:
    - amzn2-epel
    - ch_collections.base.os_package_control
    - ch_collections.base.pip
    - ch_collections.base.clamav
    - cloudwatch-agent
    - role: ansible-cis-amazon-linux-2
      cis_target_os_versions: 
        - "2"
    - ch_collections.base.nagios_nrpe_client
