---
- name: Check if EPEL repo is already configured.
  stat:
    path: "{{ epel_repofile_path }}"
  register: epel_repofile_result

- name: Install EPEL repo
  command: amazon-linux-extras install epel -y
  when: not epel_repofile_result.stat.exists

- name: Setting Repo Priorities
  lineinfile:
    path: "{{ epel_repofile_path }}"
    line: "priority={{ epel_repo_priority }}"
    insertafter: '^\[epel\]$'
    regexp: "^priority=.*$"
    state: present
  when: set_epel_repo_priority
